routes/admin.php
<?php

Route::get('dashboard', 'ShowDashboard')->name('dashboard');
Route::resource('posts', 'PostController');
Route::delete('/posts/{post}/thumbnail', 'PostThumbnailController@destroy')->name('posts_thumbnail.destroy');
Route::resource('users', 'UserController')->only(['index', 'edit', 'update']);
Route::resource('comments', 'CommentController')->only(['index', 'edit', 'update', 'destroy']);
Route::resource('media', 'MediaLibraryController')->only(['index', 'show', 'create', 'store', 'destroy']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'PostController@index')->name('home');
Route::get('/posts/feed', 'PostFeedController@index')->name('posts.feed');
Route::resource('posts', 'PostController')->only('show');
Route::resource('users', 'UserController')->only('show');

Route::get('newsletter-subscriptions/unsubscribe', 'NewsletterSubscriptionController@unsubscribe')->name('newsletter-subscriptions.unsubscribe');

resources/views/admin/dashboard/_comments.blade.php
@component('components.cards.default', ['class' => 'bg-primary text-light m-2'])
    <div class="row justify-content-between">
        <i class="fa fa-comments fa-5x" aria-hidden="true"></i>
        <div class="text-right">
            <div class="huge">{{ $comments->count() }}</div>
            <div>{{ trans_choice('comments.new_comments', $comments->count()) }}</div>
        </div>
    </div>

    @slot('footer')
        <a href="{{ route('admin.comments.index') }}" class="d-flex justify-content-between text-light">
            <span>@lang('dashboard.details')</span>
            <span><i class="fa fa-arrow-circle-right"></i></span>
        </a>
    @endslot
@endcomponent

resources/views/admin/dashboard/_posts.blade.php
@component('components.cards.default', ['class' => 'bg-success text-light m-2'])
    <div class="row justify-content-between">
        <i class="fa fa-file-text fa-5x" aria-hidden="true"></i>
        <div class="text-right">
            <div class="huge">{{ $posts->count() }}</div>
            <div>{{ trans_choice('posts.new_posts', $posts->count()) }}</div>
        </div>
    </div>

    @slot('footer')
        <a href="{{ route('admin.posts.index') }}" class="d-flex justify-content-between text-light">
            <span>@lang('dashboard.details')</span>
            <span><i class="fa fa-arrow-circle-right"></i></span>
        </a>
    @endslot
@endcomponent

resources/views/admin/dashboard/_users.blade.php
@component('components.cards.default', ['class' => 'bg-warning text-light m-2'])
    <div class="row justify-content-between">
        <i class="fa fa-users fa-5x" aria-hidden="true"></i>
        <div class="text-right">
            <div class="huge">{{ $users->count() }}</div>
            <div>{{ trans_choice('users.new_users', $users->count()) }}</div>
        </div>
    </div>

    @slot('footer')
        <a href="{{ route('admin.users.index') }}" class="d-flex justify-content-between text-light">
            <span>@lang('dashboard.details')</span>
            <span><i class="fa fa-arrow-circle-right"></i></span>
        </a>
    @endslot
@endcomponent

resources/views/admin/dashboard/index.blade.php
@extends('admin.layouts.app')

@section('content')
  <div class="page-header">
    <h1>@lang('dashboard.this_week')</h1>
  </div>

  <div class="row">
    <div class="col-xl-4 col-sm-6 mb-3">
      @include('admin/dashboard/_posts')
    </div>

    <div class="col-xl-4 col-sm-6 mb-3">
      @include('admin/dashboard/_comments')
    </div>

    <div class="col-xl-4 col-sm-6 mb-3">
      @include('admin/dashboard/_users')
    </div>
  </div>
@endsection